export const LOGIN_STATUS='LOGIN_STATUS';
export const REDUX_SETUP='REDUX_SETUP';
export const FEATURED_QUESTIONS='FEATURED_QUESTIONS';
export const GET_USER_DETAILS ='GET_USER_DETAILS';
export const USER_TAGS_DETAILS='USER_TAGS_DETAILS';
export const USER_QUESTION_DETAILS='USER_QUESTION_DETAILS';


